#!/usr/bin/env bash
# restore-secrets.sh — pull secrets from Bitwarden into ~/.config/polysim/.
#
# Files written (chmod 600):
#   ~/.config/polysim/env.sh          — shell env (DB URLs, API keys, etc.)
#   ~/.config/polysim/mcp-secrets.sh  — MCP server tokens
#   ~/.config/polysim/gh-token        — GitHub PAT for `gh auth login --with-token`
#   ~/.config/polysim/.bw-session     — short-lived BW session token (chmod 600)
#
# Bootstrap (one-time per machine):
#   export BW_CLIENTID=user.xxxxxxxx
#   export BW_CLIENTSECRET=xxxxxxxxxxxxxxxxxxxx
#   export BW_PASSWORD=...                       # vault master password
#   ./bootstrap/restore-secrets.sh
#
# After first run BW credentials remain only in this shell — never written to disk.
# The session token IS persisted (chmod 600) so subsequent runs can refresh.

set -euo pipefail

log()  { printf '\033[1;34m[secrets]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n'    "$*" >&2; }
die()  { printf '\033[1;31m[fail]\033[0m %s\n'    "$*" >&2; exit 1; }

command -v bw >/dev/null 2>&1 || die "bw (Bitwarden CLI) not installed. Run bootstrap/install.sh first."
command -v jq >/dev/null 2>&1 || die "jq not installed."

CFG_DIR="${POLYSIM_CFG_DIR:-$HOME/.config/polysim}"
mkdir -p "$CFG_DIR"
chmod 700 "$CFG_DIR"

SESSION_FILE="$CFG_DIR/.bw-session"

# ---------------------------- login + unlock ---------------------------------

bw_status() { bw status 2>/dev/null | jq -r '.status' 2>/dev/null || echo "unknown"; }

status="$(bw_status)"
log "Bitwarden status: $status"

case "$status" in
  unauthenticated)
    [ -n "${BW_CLIENTID:-}" ] && [ -n "${BW_CLIENTSECRET:-}" ] \
      || die "Set BW_CLIENTID and BW_CLIENTSECRET env vars (Bitwarden API key)."
    log "Logging in via API key…"
    bw login --apikey >/dev/null
    ;;
  locked|unlocked) ;;
  *) die "Unexpected bw status: $status" ;;
esac

if [ "$(bw_status)" = "locked" ] || [ -z "${BW_SESSION:-}" ]; then
  [ -n "${BW_PASSWORD:-}" ] || die "Set BW_PASSWORD env var to unlock the vault."
  log "Unlocking vault…"
  BW_SESSION="$(bw unlock --raw --passwordenv BW_PASSWORD)"
  export BW_SESSION
  umask 077
  printf '%s' "$BW_SESSION" > "$SESSION_FILE"
  chmod 600 "$SESSION_FILE"
fi

bw sync >/dev/null
log "Vault synced."

# ---------------------------- helpers ----------------------------------------

# get_field <item-name> <field-name>
get_field() {
  local item="$1" field="$2"
  bw get item "$item" 2>/dev/null \
    | jq -r --arg f "$field" '
        (.fields // []) as $fs
        | (if (.login.password // "") != "" and ($f == "password") then .login.password
           elif (.login.username // "") != "" and ($f == "username") then .login.username
           elif (.notes // "") != "" and ($f == "notes") then .notes
           else (($fs[] | select(.name==$f) | .value) // "")
           end)' 2>/dev/null
}

# get_password <item-name>
get_password() {
  bw get password "$1" 2>/dev/null || true
}

write_secret_file() {
  local path="$1"; shift
  umask 077
  printf '%s\n' "$@" > "$path"
  chmod 600 "$path"
  log "Wrote $path"
}

# ---------------------------- env.sh -----------------------------------------
#
# Items below are LOOKED UP BY NAME in your Bitwarden vault. Adjust names to
# match your vault, or override via the POLYSIM_BW_* env vars at the top.

POLYSIM_BW_DB_URL_ITEM="${POLYSIM_BW_DB_URL_ITEM:-polysim/database-url}"
POLYSIM_BW_OPENAI_ITEM="${POLYSIM_BW_OPENAI_ITEM:-polysim/openai-api-key}"
POLYSIM_BW_ANTHROPIC_ITEM="${POLYSIM_BW_ANTHROPIC_ITEM:-polysim/anthropic-api-key}"
POLYSIM_BW_GH_ITEM="${POLYSIM_BW_GH_ITEM:-polysim/github-pat}"

DB_URL="$(get_password "$POLYSIM_BW_DB_URL_ITEM")"
OPENAI_KEY="$(get_password "$POLYSIM_BW_OPENAI_ITEM")"
ANTHROPIC_KEY="$(get_password "$POLYSIM_BW_ANTHROPIC_ITEM")"
GH_TOKEN="$(get_password "$POLYSIM_BW_GH_ITEM")"

write_secret_file "$CFG_DIR/env.sh" \
  "# generated by restore-secrets.sh — do not commit" \
  "export DATABASE_URL='${DB_URL}'" \
  "export OPENAI_API_KEY='${OPENAI_KEY}'" \
  "export ANTHROPIC_API_KEY='${ANTHROPIC_KEY}'"

# ---------------------------- mcp-secrets.sh ---------------------------------

POLYSIM_BW_GRAFANA_ITEM="${POLYSIM_BW_GRAFANA_ITEM:-polysim/grafana-api-key}"
POLYSIM_BW_SUPABASE_ITEM="${POLYSIM_BW_SUPABASE_ITEM:-polysim/supabase-access-token}"
POLYSIM_BW_DOKPLOY_ITEM="${POLYSIM_BW_DOKPLOY_ITEM:-polysim/dokploy-api-token}"

GRAFANA_KEY="$(get_password "$POLYSIM_BW_GRAFANA_ITEM")"
SUPABASE_TOKEN="$(get_password "$POLYSIM_BW_SUPABASE_ITEM")"
DOKPLOY_TOKEN="$(get_password "$POLYSIM_BW_DOKPLOY_ITEM")"

write_secret_file "$CFG_DIR/mcp-secrets.sh" \
  "# generated by restore-secrets.sh — do not commit" \
  "export GRAFANA_API_KEY='${GRAFANA_KEY}'" \
  "export SUPABASE_ACCESS_TOKEN='${SUPABASE_TOKEN}'" \
  "export DOKPLOY_API_TOKEN='${DOKPLOY_TOKEN}'"

# ---------------------------- gh token ---------------------------------------

if [ -n "$GH_TOKEN" ]; then
  write_secret_file "$CFG_DIR/gh-token" "$GH_TOKEN"
  if command -v gh >/dev/null 2>&1 && ! gh auth status >/dev/null 2>&1; then
    log "Authenticating gh with stored token…"
    gh auth login --with-token < "$CFG_DIR/gh-token" || warn "gh auth failed"
  fi
fi

log "Done. Source the env files in your shell:"
log "  . $CFG_DIR/env.sh"
log "  . $CFG_DIR/mcp-secrets.sh"
