#!/usr/bin/env bash
# sync-secrets.sh — pull polysimulator secrets from Bitwarden Secrets Manager
# and write them to <polysimulator-repo>/.env, layered with env-specific defaults.
#
# Layering (last assignment wins for duplicate keys, per docker-compose semantics):
#   1. <polysim-repo>/.env.defaults              (env-agnostic, optional)
#   2. <polysim-repo>/.env.defaults.<env>        (env-specific, optional)
#   3. bws secret list -o env                    (secrets, always — highest precedence)
#
# Usage:
#   ./bootstrap/sync-secrets.sh                  # default: --env dev
#   ./bootstrap/sync-secrets.sh --env prod
#   ./bootstrap/sync-secrets.sh --env staging-api
#   ./bootstrap/sync-secrets.sh -e dev
#
# Replaces the legacy bw (personal vault) flow. Secret keys in bws must match
# the env var names the app expects — no prefix translation.
#
# Prerequisites (handled by ./bootstrap/install.sh):
#   - bws CLI on PATH
#
# Auth resolution (in order):
#   - $BWS_ACCESS_TOKEN env var
#   - ~/.config/polysim/bws-token (chmod 600)
#
# Project resolution (in order):
#   - $BWS_PROJECT_ID env var
#   - ~/.config/polysim/bws-project-id
#   - if neither: lists available projects and exits non-zero
#
# Output:
#   <polysimulator-repo>/.env (chmod 600, gitignored)
#
# Override polysimulator location with POLYSIM_REPO_DIR.

set -euo pipefail

log()  { printf '\033[1;34m[sync]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

# ---- parse args -----------------------------------------------------------

ENV_NAME="dev"
while [ $# -gt 0 ]; do
  case "$1" in
    --env|-e)  [ $# -ge 2 ] || die "--env requires a value (e.g. --env prod)"
               ENV_NAME="$2"; shift 2 ;;
    --env=*)   ENV_NAME="${1#*=}"; shift ;;
    -h|--help) sed -n '2,38p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)         die "Unknown argument: $1 (use --help for usage)" ;;
  esac
done

case "$ENV_NAME" in
  ''|*[!a-zA-Z0-9_-]*) die "Invalid --env value: '$ENV_NAME' (alphanumeric, dash, underscore only)" ;;
esac

CFG_DIR="$HOME/.config/polysim"
TOKEN_FILE="$CFG_DIR/bws-token"
PROJECT_FILE="$CFG_DIR/bws-project-id"

# ---- resolve auth ---------------------------------------------------------

if [ -z "${BWS_ACCESS_TOKEN:-}" ] && [ -r "$TOKEN_FILE" ]; then
  BWS_ACCESS_TOKEN="$(cat "$TOKEN_FILE")"
  export BWS_ACCESS_TOKEN
fi

if [ -z "${BWS_ACCESS_TOKEN:-}" ]; then
  die "BWS_ACCESS_TOKEN not set and $TOKEN_FILE not found.
Get a machine-account token from sm.bitwarden.com, then either:
  export BWS_ACCESS_TOKEN=<token>
or persist it:
  mkdir -p $CFG_DIR && printf '%s\n' '<token>' > $TOKEN_FILE && chmod 600 $TOKEN_FILE"
fi

# ---- check tools ----------------------------------------------------------

command -v bws >/dev/null 2>&1 \
  || die "bws not installed — run ./bootstrap/install.sh first"

# ---- resolve project id ---------------------------------------------------

if [ -z "${BWS_PROJECT_ID:-}" ] && [ -r "$PROJECT_FILE" ]; then
  BWS_PROJECT_ID="$(cat "$PROJECT_FILE")"
fi

if [ -z "${BWS_PROJECT_ID:-}" ]; then
  warn "BWS_PROJECT_ID not set. Available projects:"
  bws project list >&2 || true
  die "Set BWS_PROJECT_ID=<uuid>, or persist it:
  mkdir -p $CFG_DIR && printf '%s\n' '<uuid>' > $PROJECT_FILE"
fi

# ---- locate target repo ---------------------------------------------------

REPO_DIR="${POLYSIM_REPO_DIR:-$HOME/projects/polysimulator}"
[ -d "$REPO_DIR" ] \
  || die "polysimulator repo not found at $REPO_DIR
Clone it first:
  gh repo clone Bavariance/polysimulator $REPO_DIR
Or override with POLYSIM_REPO_DIR=/path/to/polysimulator $0"

DEFAULTS_FILE="$REPO_DIR/.env.defaults"
ENV_DEFAULTS_FILE="$REPO_DIR/.env.defaults.$ENV_NAME"
OUT_FILE="$REPO_DIR/.env"

# ---- fetch secrets --------------------------------------------------------

log "Environment: $ENV_NAME"
log "Fetching secrets from bws (project $BWS_PROJECT_ID)…"
SECRETS_ENV="$(bws secret list -o env "$BWS_PROJECT_ID" 2>&1)" \
  || die "bws fetch failed:
$SECRETS_ENV"

SECRET_COUNT="$(printf '%s\n' "$SECRETS_ENV" | grep -cE '^[A-Z_][A-Z0-9_]*=' || true)"
[ "$SECRET_COUNT" -gt 0 ] \
  || die "bws returned 0 secrets — check the project ID and machine-account access"

# ---- write .env atomically -------------------------------------------------

umask 077
TMP="$(mktemp "$REPO_DIR/.env.sync.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

{
  printf '# Generated by polysim-bootstrap/bootstrap/sync-secrets.sh\n'
  printf '# DO NOT EDIT MANUALLY — re-run sync-secrets.sh after rotating any secret\n'
  printf '# or changing a defaults file.\n'
  printf '#\n'
  printf '# Layered (last wins for duplicate keys):\n'
  printf '#   1. .env.defaults                  (env-agnostic)\n'
  printf '#   2. .env.defaults.%s               (env-specific)\n' "$ENV_NAME"
  printf '#   3. bws secret list -o env         (secrets)\n'
  printf '#\n'
  printf '# Environment: %s\n' "$ENV_NAME"
  printf '# bws project: %s\n' "$BWS_PROJECT_ID"
  printf '# Generated:   %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  if [ -r "$DEFAULTS_FILE" ]; then
    printf '# ====== %s ======\n' "$(basename "$DEFAULTS_FILE")"
    cat "$DEFAULTS_FILE"
    printf '\n'
  else
    printf '# (no .env.defaults found — skipping env-agnostic defaults layer)\n\n'
  fi

  if [ -r "$ENV_DEFAULTS_FILE" ]; then
    printf '# ====== %s ======\n' "$(basename "$ENV_DEFAULTS_FILE")"
    cat "$ENV_DEFAULTS_FILE"
    printf '\n'
  else
    printf '# (no %s found — skipping env-specific defaults layer)\n\n' "$(basename "$ENV_DEFAULTS_FILE")"
  fi

  printf '# ====== secrets from bws ======\n'
  printf '%s\n' "$SECRETS_ENV" | grep -E '^[A-Z_][A-Z0-9_]*=' | LC_ALL=C sort
} > "$TMP"

mv "$TMP" "$OUT_FILE"
chmod 600 "$OUT_FILE"
trap - EXIT

log "Wrote $OUT_FILE ($SECRET_COUNT secrets, $(wc -l < "$OUT_FILE") total lines, chmod 600)"
log "Done. 'docker compose up' will pick up the new env."
