#!/usr/bin/env bash
# sync-secrets.sh — pull polysimulator secrets from Bitwarden Secrets Manager
# and write them to <polysimulator-repo>/.env.
#
# Replaces the legacy bw (personal vault) flow. Secret keys in bws must match
# the env var names the app expects — no prefix translation.
#
# Prerequisites (handled by ./bootstrap/install.sh):
#   - bws CLI on PATH
#   - jq (used only for the project-listing fallback)
#
# Auth resolution (in order):
#   - $BWS_ACCESS_TOKEN env var
#   - ~/.config/polysim/bws-token (chmod 600)
#
# Project resolution (in order):
#   - $BWS_PROJECT_ID env var
#   - ~/.config/polysim/bws-project-id
#   - if neither: lists available projects and exits non-zero
#
# Output:
#   <polysimulator-repo>/.env (chmod 600)
#   Optionally prepends <polysimulator-repo>/.env.defaults if it exists.
#
# Override polysimulator location with POLYSIM_REPO_DIR.

set -euo pipefail

log()  { printf '\033[1;34m[sync]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

CFG_DIR="$HOME/.config/polysim"
TOKEN_FILE="$CFG_DIR/bws-token"
PROJECT_FILE="$CFG_DIR/bws-project-id"

# ---- resolve auth ---------------------------------------------------------

if [ -z "${BWS_ACCESS_TOKEN:-}" ] && [ -r "$TOKEN_FILE" ]; then
  BWS_ACCESS_TOKEN="$(cat "$TOKEN_FILE")"
  export BWS_ACCESS_TOKEN
fi

if [ -z "${BWS_ACCESS_TOKEN:-}" ]; then
  die "BWS_ACCESS_TOKEN not set and $TOKEN_FILE not found.
Get a machine-account token from sm.bitwarden.com, then either:
  export BWS_ACCESS_TOKEN=<token>
or persist it:
  mkdir -p $CFG_DIR && printf '%s\n' '<token>' > $TOKEN_FILE && chmod 600 $TOKEN_FILE"
fi

# ---- check tools ----------------------------------------------------------

command -v bws >/dev/null 2>&1 \
  || die "bws not installed — run ./bootstrap/install.sh first"

# ---- resolve project id ---------------------------------------------------

if [ -z "${BWS_PROJECT_ID:-}" ] && [ -r "$PROJECT_FILE" ]; then
  BWS_PROJECT_ID="$(cat "$PROJECT_FILE")"
fi

if [ -z "${BWS_PROJECT_ID:-}" ]; then
  warn "BWS_PROJECT_ID not set. Available projects:"
  bws project list >&2 || true
  die "Set BWS_PROJECT_ID=<uuid>, or persist it:
  mkdir -p $CFG_DIR && printf '%s\n' '<uuid>' > $PROJECT_FILE"
fi

# ---- locate target repo ---------------------------------------------------

REPO_DIR="${POLYSIM_REPO_DIR:-$HOME/projects/polysimulator}"
[ -d "$REPO_DIR" ] \
  || die "polysimulator repo not found at $REPO_DIR
Clone it first:
  gh repo clone Bavariance/polysimulator $REPO_DIR
Or override with POLYSIM_REPO_DIR=/path/to/polysimulator $0"

DEFAULTS_FILE="$REPO_DIR/.env.defaults"
OUT_FILE="$REPO_DIR/.env"

# ---- fetch secrets --------------------------------------------------------

log "Fetching secrets from bws (project $BWS_PROJECT_ID)…"
SECRETS_ENV="$(bws secret list -o env "$BWS_PROJECT_ID" 2>&1)" \
  || die "bws fetch failed:
$SECRETS_ENV"

SECRET_COUNT="$(printf '%s\n' "$SECRETS_ENV" | grep -cE '^[A-Z_][A-Z0-9_]*=' || true)"
[ "$SECRET_COUNT" -gt 0 ] \
  || die "bws returned 0 secrets — check the project ID and machine-account access"

# ---- write .env atomically -------------------------------------------------

umask 077
TMP="$(mktemp "$REPO_DIR/.env.sync.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

{
  printf '# Generated by polysim-bootstrap/bootstrap/sync-secrets.sh\n'
  printf '# DO NOT EDIT MANUALLY — re-run sync-secrets.sh after rotating any secret.\n'
  printf '# Source: Bitwarden Secrets Manager project %s\n' "$BWS_PROJECT_ID"
  printf '# Generated: %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  if [ -r "$DEFAULTS_FILE" ]; then
    printf '# ====== defaults from %s ======\n' "$(basename "$DEFAULTS_FILE")"
    cat "$DEFAULTS_FILE"
    printf '\n'
  fi

  printf '# ====== secrets from bws ======\n'
  printf '%s\n' "$SECRETS_ENV" | grep -E '^[A-Z_][A-Z0-9_]*=' | LC_ALL=C sort
} > "$TMP"

mv "$TMP" "$OUT_FILE"
chmod 600 "$OUT_FILE"
trap - EXIT

log "Wrote $OUT_FILE ($SECRET_COUNT secrets, $(wc -l < "$OUT_FILE") total lines, chmod 600)"
log "Done. 'docker compose up' will pick up the new env."
